version: "3.8"

services:
  browserless:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=20
      - CONNECTION_TIMEOUT=60000
    ports:
      - "3000:3000"
    networks:
      - ht-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  ht-net:
    external: true